### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by DerThorsten**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by martinRenou — CHANGES_REQUESTED** [review]
The build number needs to be increased

**Comment by martinRenou** [comment]
Closing as you should open this PR from a fork, as the bot suggests. Also, adding the hatch dependency should come with the 3.0.0 release probably?

**Comment by DerThorsten** [comment]
> Closing as you should open this PR from a fork, as the bot suggests. 

RIght..I knew something felt wrong =)

> Also, adding the hatch dependency should come with the 3.0.0 release probably?

not sure what you mean

**Comment by martinRenou** [comment]
I mean we should both update the recipe to 3.0.0 and add the hatch dependency in the same PR?

**Pull request closed without merging**
